@startuml
title DFDレベル2（P6_通知管理処理）

left to right direction

node "モバイルOS\n(通知機構)" as OS

rectangle P6 as "P6_通知管理処理" {

  rectangle P6_1 as "P6-1_OS通知許可"
  rectangle P6_2 as "P6-2_OS通知登録"

}
rectangle P1 as "P1_初回起動／設定処理"
rectangle P2 as "P2_アプリ起動時判定処理"
rectangle P4 as "P4_FB入力処理"

' ===== 入力 =====
P1 --> P6_2 : 通知時刻
P1 --> P6_1 : 通知許可リクエスト
P2 --> P6_2 : 通知時刻
P4 --> P6_2 : 通知時刻


' ===== OS連携 =====
P6_1 --> OS : 通知許可リクエスト
P6_2 --> OS : 通知登録／更新

@enduml
