@startuml
title DFDレベル2（P2_アプリ起動時判定処理）

left to right direction
' skinparam linetype ortho 

database "データストア" as DB
node "モバイルOS\n(時刻)" as OS

rectangle P2 as "P2_アプリ起動時判定処理" {
  rectangle P2_1 as "P2-1_初回起動判定"
  rectangle P2_2 as "P2-2_日付変更判定"
  rectangle P2_3 as "P2-3_当日データ生成"
}
rectangle P6 as "P6_通知管理処理"

' ===== 入力 =====
DB -[dotted]-> P2_1 : MD:マスターデータ(初回起動フラグ)

OS -[dotted]-> P2_2 : 現在時刻
DB -[dotted]-> P2_2 : MD:マスターデータ(最終利用日)

DB -[dotted]-> P2_3 : DD:日別データ(最終利用日)

' ===== プロセス間連携 =====

P2_2 --> P2_3 : 日付変更有無


' ===== 出力 =====
P2_2 --> DB : MD:マスターデータ(最終利用日更新)
P2_3 --> DB : DD:日別データ(当日)
P2_3 --> P6 : 通知時刻

@enduml
