@startuml
title DFDレベル2（P5_通知時刻算出処理）

left to right direction


rectangle P5 as "P5_通知時刻算出処理" {
  rectangle P5_1 as "P5-1_初回通知時刻算出"
  rectangle P5_2 as "P5-2_通知時刻算出"
  rectangle P5_3 as "P5-3_通知スケジュール"
}

rectangle P1 as "P1_初回起動／設定処理"
rectangle P4 as "P4_FB入力処理"
rectangle P6 as "P6_通知管理処理"


' ===== データ取得 =====
P1 --> P5_1 :終業時間帯・就寝時間帯
P4 --> P5_2 : 当日通知時刻/FB入力内容

' ===== プロセス間連携 =====
P5_1 --> P5_3 : 通知時刻
P5_1 --> P1 : 通知時刻
P5_2 --> P5_3 : 通知時刻
P5_2 --> P4 : 通知時刻

P5_3 -> P6 : 通知時刻

@enduml
