@startuml
title DFDレベル2（P1_初回起動／設定処理）

left to right direction

actor ユーザー

node "モバイルOS\n(時刻)" as OS_Time
database "データストア" as DB

rectangle P1 as "P1_初回起動／設定処理" {

  rectangle P1_1 as "P1-1_ユーザー設定入力"
  rectangle P1_2 as "P1-2_通知許可要求"
  rectangle P1_3 as "P1-3_初期状態データ生成"
  rectangle P1_4 as "P1-4_初回起動完了処理"

}

rectangle P5 as "P5_通知時刻算出処理"
rectangle P6 as "P6_通知管理処理"

' ===== ユーザーとの入出力 =====
ユーザー --> P1_1 : 終業時間帯\n就寝時間帯
ユーザー --> P1_2 : 通知許可・不許可選択

' ===== OSとの入出力 =====
P1_2 --> P6 : 通知許可リクエスト
OS_Time --> P1_3 : 現在時刻

' ===== プロセス間連携 =====
P1_1 --> P1_3 : 設定値
P1_3 --> P1_4 : 初期データ

P1_3 -[dotted]-> P5 : 終業時間帯・就寝時間帯
P5 --> P1_3 : 通知時刻


' ===== データストア =====
P1_4 --> DB : MD:マスターデータ\nDD:日別データ(当日)

@enduml
