@startuml
title 日付変更時 処理シーケンス（通知再計算なし・逆探索方式）

participant "EntryService" as Entry
participant "AppStartService\n(P2)" as P2
participant "Repository\n(SQLite)" as DB
participant "OS\n(時刻)" as OS_Time
participant "OS\n(通知)" as OS_Notify

== 日付変更判定 ==
Entry -> P2 : handleDateChange()
P2 -> OS_Time : 現在日付取得
P2 -> DB : 最終利用日取得
P2 -> P2 : IsDateChanged()

alt 日付け変更あり
  P2 -> P2 : ProcessDateChange()
  P2 -> DB : 昨日のデータを取得
    alt 昨日のデータなし
      P2 -> DB : 最終利用日取得
      DB --> P2 : lastUsed
      loop 最新のデータ取得まで
        P2 -> P2 : searchDate = yesterday - n
        alt データあり
        P2 -> DB : getByDate(searchDate)
        DB --> P2 : lastNotifyTime = found
        else データなし
        P2 --> P2 : lastNotifyTime = DefaultTime
        end // データなし
      end
      P2 -> OS_Notify : 通知スケジュール更新(lastNotifyTime)
      P2 -> DB : lastNotifyTimeで今日のデータを作成
    else 昨日のデータあり
      P2 -> DB : 今日のデータ取得
      DB --> P2 : todayState       
      alt todayStateなし = Feedback無し
      P2 -> OS_Notify : 通知スケジュール更新(yesterdayState.NotifyTime)
      P2 -> DB : yesterdayState.NotifyTimeで今日のデータを作成
  end
end

end


@enduml
