@startuml
title 01_アプリ起動時 処理フロー

start

:アプリ起動;

if (初回起動フラグON?) then (Yes)
   #LightBlue:[02_初回起動時フロー]実行;
else

' --- 日付変更チェック ---
:現在日付取得;
:最終利用日取得;

if (現在日付 ≠ 最終利用日?) then (Yes)
  #LightBlue:[03_日付変更時フロー]実行;
endif

endif
' --- 通常起動フロー ---

#LightGreen:当日状態データ取得;
note right
・通知時刻
・FB完了フラグ
end note

if (FB完了状態 = true?) then (Yes)
  :「今日もお疲れさまでした。」表示;
  note right
    状態 = S3
  end note

else (No)

  if (現在時刻 < 通知時刻?) then (Yes)
    :「まだまだ頑張りましょう！」表示;
    note right
      状態 = S1
    end note

  else (No)
    :FB画面表示;
    note right
      状態 = S2
    end note

    if (FB送信完了?) then (Yes)
      :FB内容を保存;
      :FB完了状態 = true;
      #LightBlue: [04_通知時刻算出フロー]へ;
      #LightGreen:[当日状態データ取得]へ戻る;
       end
    endif
  endif

endif

stop
@enduml
