@startuml
title 03_日付変更時 処理フロー（loop構文対応）

start

:日付変更検知;

:最終利用日を更新;

:昨日の状態を取得;

if (昨日の状態あり(=未利用日無し)) then (No)

  :処理対象日 = 昨日;

  while (処理対象日 > 最終利用日) is (Yes)
    :処理対象日の状態を取得;
    if (処理対象日の状態あり) then (Yes)
      :最終利用日の通知時刻を取得;
      break
    else (No)
      :処理対象日を1日戻す;
    endif
  endwhile (No)
  :今日の状態を作成;
  note right
    ・通知時刻は最終利用日の通知時刻を引き継ぐ
    ・FB完了フラグはfalseで初期化
  end note
  :今日の状態を保存;

else (Yes)
  :今日の状態を取得;
  if (今日の状態あり) then (Yes)
    note right
      当日状態あり=前日のFeedBack時に作成済
    end note
  else (No)
    :今日の状態を更新;
    note left
    ・通知時刻は昨日と同じ時刻(暫定)
    ・FB完了フラグはfalseで初期化
  end note
    :今日の状態を保存;
  endif
endif



stop
@enduml
