@startuml
title 通知時間調整ロジック フローチャート

start

:当日通知時間を取得;

if (FBは入力されたか？) then (No)
  :翌日通知時間 = 当日通知時間;
  
else (Yes)


if (FB種別は②「ありがとう」？) then (Yes)
  :翌日通知時間 = 当日通知時間;
else (No)


if (FB種別は①「まだまだ頑張れる」？) then (Yes)
  :調整方向 = ＋;
else (FB③「なんで今頃」)
  :調整方向 = −;
endif

:調整量（分）を取得;
:仮翌日通知時間 = 当日通知時間 ± 調整量;

if (終業時間帯開始 >= 仮翌日通知時間？) then (Yes)
  :仮翌日通知時間＝終業時間帯開始時刻;
endif

if (就寝時間帯が設定されている？) then (Yes)
  if (仮翌日通知時間 >= 就寝時間帯開始？) then (Yes)
    :仮翌日通知時間 =\n就寝時間帯開始;
  endif
endif

:翌日通知時間 = 仮翌日通知時間;
endif 
endif

stop

@enduml