@startuml
title モジュール構成図
' left to right direction
skinparam linetype ortho

package "ロジック層" {
    [初回起動時処理]
    [通知時刻到達処理]
    [FB送信処理]
    [通知時刻算出処理]
    [状態遷移処理]
}

package "UI層"{
    [メッセージ通知画面]
    [チュートリアル画面]
    [FB画面]
}

package "通知管理層" {
    [通知スケジューラ設定]
}

package "データ管理層"{
    [ユーザ設定管理]
    [FB履歴管理]
}

"UI層" --> "ロジック層"
"ロジック層" -> "データ管理層"
"ロジック層" --> "通知管理層"


@enduml
